Pytest migration
boto/botocore pull request #2209
Opened 2020-11-09 17:47 UTC by zdutta

Migrating testing suite from nose to pytest. Split into 4 commits: functional, integration, unit pt1 and unit pt2

2020-11-09 23:52 UTC, nateprewitt requested changes
Only about 1/5 of the way through but wanted to leave this now to cut down on iterations.

2020-11-10 03:04 UTC, joguSD commented on tests/functional/csm/test_monitoring.py
> +TEST_CASES = []
I think this just forgot to be deleted.

2020-11-10 03:10 UTC, joguSD commented on tests/functional/retries/test_bucket.py
> +        assert any(x < (0.2 * mean) for x in distribution) is False
Any reason to to not use `assert not any`?

2020-11-10 03:11 UTC, joguSD commented on tests/functional/test_apigateway.py
> +            assert request.headers.get('Accept') == b'application/yaml'
Kind of strange that the newline got removed.

2020-11-10 03:12 UTC, joguSD commented on tests/functional/test_cloudsearchdomain.py
> +            assert request.headers.get('Content-Type') == content_type
Another removal of the new line.

2020-11-10 03:14 UTC, joguSD commented on tests/functional/test_credentials.py
> +            assert creds[0] == creds[1] == creds[2]
Is there a particular you ran into that made you remove the failure messages when porting to `assert`?

2020-11-10 03:17 UTC, joguSD commented on tests/functional/test_credentials.py
> +        self.env_provider.load.call_count == 1
Looks like we forgot to `assert` here.

2020-11-10 03:45 UTC, joguSD commented on tests/integration/test_emr.py
> +@pytest.mark.parametrize('region',['us-east-1', 'us-west-2', 'ap-northeast-1',
Might be easier to just pull this list out as a `EMR_REGIONS` variable at the module level or something.

2020-11-10 03:45 UTC, joguSD commented on tests/integration/test_emr.py
> +        assert isinstance(page_iterator ,PageIterator)
Nit: looks like the whitespace around the comma got flipped.

2020-11-10 04:10 UTC, joguSD commented
Overall the changes seem reasonable, looks like there's some failures though? Maybe related to a parameterize migration? 
Also looks like the CI is broken on 2.7, though we're still using travis on this branch. Let's get this passing on Python 3 and then we'll merge and rebase the migration branch to include the migration to github actions and we'll address fixing the 2.7 failure the

2020-11-10 04:10 UTC, joguSD commented
Overall the changes seem reasonable, looks like there's some failures though? Maybe related to a parameterize migration? 
Also looks like the CI is broken on 2.7, though we're still using travis on this branch. Let's get this passing on Python 3 and then we'll merge and rebase the migration branch to include the migration to github actions and we'll address fixing the 2.7 failures then.

2020-11-12 20:24 UTC, joguSD commented
This looks good to me, I'm not too concerned about travis failing right now -- let's get CI fully functional again once we rebase on top of develop and make sure we're working under github actions.

2020-11-12 20:24 UTC, joguSD approved these changes

2020-11-13 19:01 UTC, merged