Fixes boto/botocore#2468 issue, corrected v2 signature of get_object_lock_configuration
boto/botocore pull request #2469
Opened 2021-08-26 09:34 UTC by lucasso

"?object-lock" part of request URL is now correctly included in "string_to_sign" in HmacV1Auth signer

2021-09-22 17:27 UTC, nateprewitt requested changes
Hey @lucasso, thanks for the PR! Would you be able to add a test or two codifying this change? That will help ensure this behavior doesn't regress in the future.

2021-09-23 12:20 UTC, lucasso commented
Working on a unittest. I should finish in a week.

2021-10-04 20:47 UTC, lucasso commented
Added a unittest. Fails without a change with:
```
======================================================================
FAIL: test_bucket_operations (tests.unit.auth.test_signers.TestHMACV1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vpnuser/repos/botocore/tests/unit/auth/test_signers.py", line 107, in test_bucket_operations
    self.assertEqual(cr, '/quotes?%s' % operation)
AssertionError: '/quotes' != '/quotes?object-lock'
- /quotes
+ /quotes?object-lock
```
and passes with the change

2021-10-06 17:25 UTC, nateprewitt approved these changes
Thanks @lucasso! I think this looks good.

2021-10-06 17:33 UTC, merged