This change fixes region redirect issues for opt-in regions
boto/botocore pull request #3303
Opened 2024-11-16 01:02 UTC by ubaskota

When accessing an S3 bucket from the wrong region for opt-in regions, a 400 `IllegalLocationConstraintException` error is thrown. Botocore already has a functionality to automatically redirect requests to the correct region. This fix adds an additional condition to ensure that redirection happens whenever a request is made to the wrong region from opt-in regions.

2024-11-18 22:17 UTC, SamRemis requested changes

2024-11-19 18:57 UTC, ubaskota commented on botocore/utils.py
> +            and operation.name == 'GetObject'
Thanks for pointing it out. For some reason, I was fixated only on `GetObject` and `CreateBucket` actions.

2024-11-19 21:47 UTC, SamRemis commented on botocore/utils.py
> +        is_opt_in_region = (
Nit: maybe `is_opt_in_region_redirect`?

2024-11-20 15:20 UTC, SamRemis approved these changes

2024-11-21 17:45 UTC, merged